# The name of your app. Create yours at https://appengine.google.com/start/createapp?
application: appname

runtime: python27
api_version: 1
threadsafe: true

# This is how you control where your app is deployed.
version: stable

handlers:

# serve ui/index.html for the root request
- url: /
  static_files: ui/index.html
  upload: ui/index.html

# serve index.html when a directory is requested
- url: /(.+)/
  static_files: ui/\1/index.html
  upload: ui/(.+)/index.html

# serve all other requests from the ui folder
- url: /
  static_dir: ui

